"""Domain contracts for the work capability."""

from .models import (
    AbandonRequest,
    AbandonResult,
    ApprovalRequest,
    ApprovalResult,
    AssignmentRequest,
    AssignmentResult,
    BounceRequest,
    CheckRequest,
    CheckResult,
    ClaimRequest,
    ClaimResult,
    MergeRequest,
    MergeResult,
    ResumeRequest,
    ResumeResult,
    ReviewRequest,
    ReviewResult,
    ScheduleRequest,
    ScheduleResult,
    SubmissionRequest,
    SubmissionResult,
)

__all__ = [
    "AbandonRequest",
    "AbandonResult",
    "ApprovalRequest",
    "ApprovalResult",
    "AssignmentRequest",
    "AssignmentResult",
    "BounceRequest",
    "CheckRequest",
    "CheckResult",
    "ClaimRequest",
    "ClaimResult",
    "MergeRequest",
    "MergeResult",
    "ResumeRequest",
    "ResumeResult",
    "ReviewRequest",
    "ReviewResult",
    "ScheduleRequest",
    "ScheduleResult",
    "SubmissionRequest",
    "SubmissionResult",
]
