"""Provider- and transport-neutral hive capability."""

from .application import HiveLifecycleService
from .contracts import DependencyProbe, HiveRegistry, LifecyclePublisher, WorkspaceRealizer
from .domain import (
    DiscoverHivesResult,
    HiveDiagnostic,
    HiveIdentity,
    HiveIdentityContractError,
    HiveIdentityPage,
    HiveListRequest,
    HiveListResult,
    HiveStatusRequest,
    HiveStatusResult,
    OnboardCheck,
    OnboardHiveRequest,
    OnboardHiveResult,
    ReadinessCheck,
    ReadinessRequest,
    ReadinessResult,
    RegisterHiveRequest,
    RegisterHiveResult,
    RetireEvent,
    RetireHiveRequest,
    RetireHiveResult,
    RetireScope,
    affiliation_for_kind,
    identity_record,
)

__all__ = [
    "DependencyProbe",
    "DiscoverHivesResult",
    "HiveDiagnostic",
    "HiveIdentity",
    "HiveIdentityPage",
    "HiveIdentityContractError",
    "HiveLifecycleService",
    "HiveListRequest",
    "HiveListResult",
    "HiveRegistry",
    "HiveStatusRequest",
    "HiveStatusResult",
    "LifecyclePublisher",
    "OnboardHiveRequest",
    "OnboardHiveResult",
    "OnboardCheck",
    "ReadinessCheck",
    "ReadinessRequest",
    "ReadinessResult",
    "RegisterHiveRequest",
    "RegisterHiveResult",
    "RetireEvent",
    "RetireHiveRequest",
    "RetireHiveResult",
    "RetireScope",
    "WorkspaceRealizer",
    "affiliation_for_kind",
    "identity_record",
]
