"""Stdlib-only kernel plugin slot/binding and lifecycle event contracts (bh-xh8ku.2).

Depends on nothing — not even another library package
(``docs/design/package-class-library-vs-plugin-adr.md`` section 4). Importing this package
describes metadata and typed ports; it never discovers plugins, reads configuration, inspects
the host, or imports an integration. Discovery, the lifecycle dispatcher, and telemetry stay in
``src/beadhive`` — composition machinery that binds concrete providers to the contracts here,
not part of the contracts themselves.

Root keeps forwarding facades at ``beadhive.kernel.plugins.contracts``,
``beadhive.kernel.plugins.binding``, and ``beadhive.kernel.lifecycle.contracts`` so existing
consumers keep working unchanged; every name here resolves identically through those facades.
"""

from __future__ import annotations

from .binding import bind_application_port
from .contracts import (
    BUILD_IMPACT,
    BUILD_VERIFY,
    BuildVerifier,
    CapabilityBindingError,
    CapabilityKey,
    CapabilityRef,
    CapabilitySelection,
    CliProjection,
    CredentialRequirement,
    CredentialSource,
    DiagnosticCode,
    DiagnosticSeverity,
    DiscoveredPlugin,
    DiscoveryResult,
    ExecutableRequirement,
    ExternalEntryPoint,
    LifecycleSubscriptionDeclaration,
    ManifestDocument,
    ManifestLoader,
    ManifestProvenance,
    ManifestSource,
    PermissionRequirement,
    PluginDiagnostic,
    PluginKernelConfig,
    PluginManifest,
    PortT,
    ProviderBinding,
    ProviderKey,
    SourceRead,
    Version,
    VersionRange,
)
from .lifecycle import (
    AGENT_LAUNCH_EVENTS,
    ALL_LIFECYCLE_EVENTS,
    EVENTS_BY_ID,
    HIVE_EVENTS,
    HOST_EVENTS,
    PLUGIN_EVENTS,
    WORKTREE_EVENTS,
    AgentLaunchLifecycleContext,
    AgentLaunchLifecyclePhase,
    CompensationMode,
    CompensationPolicy,
    ContextT,
    Criticality,
    DeliveryPolicy,
    HiveLifecycleContext,
    HiveLifecyclePhase,
    HostDaemonLifespanComponent,
    HostDaemonLifespanFactory,
    HostDaemonRuntimePort,
    HostDaemonShutdownPhase,
    HostDaemonStartupPhase,
    HostLifecycleContext,
    HostLifecyclePhase,
    Idempotency,
    LifecycleCompensator,
    LifecycleEvent,
    LifecycleFamily,
    LifecyclePhase,
    LifecycleSubscriber,
    PluginLifecycleContext,
    PluginLifecyclePhase,
    RetryPolicy,
    SubscriberBinding,
    WorktreeLifecycleContext,
    WorktreeLifecyclePhase,
)

__all__ = [
    "AGENT_LAUNCH_EVENTS",
    "ALL_LIFECYCLE_EVENTS",
    "BUILD_IMPACT",
    "BUILD_VERIFY",
    "EVENTS_BY_ID",
    "HIVE_EVENTS",
    "HOST_EVENTS",
    "PLUGIN_EVENTS",
    "WORKTREE_EVENTS",
    "AgentLaunchLifecycleContext",
    "AgentLaunchLifecyclePhase",
    "BuildVerifier",
    "CapabilityBindingError",
    "CapabilityKey",
    "CapabilityRef",
    "CapabilitySelection",
    "CliProjection",
    "CompensationMode",
    "CompensationPolicy",
    "ContextT",
    "CredentialRequirement",
    "CredentialSource",
    "Criticality",
    "DeliveryPolicy",
    "DiagnosticCode",
    "DiagnosticSeverity",
    "DiscoveredPlugin",
    "DiscoveryResult",
    "ExecutableRequirement",
    "ExternalEntryPoint",
    "HiveLifecycleContext",
    "HiveLifecyclePhase",
    "HostDaemonLifespanComponent",
    "HostDaemonLifespanFactory",
    "HostDaemonRuntimePort",
    "HostDaemonShutdownPhase",
    "HostDaemonStartupPhase",
    "HostLifecycleContext",
    "HostLifecyclePhase",
    "Idempotency",
    "LifecycleCompensator",
    "LifecycleEvent",
    "LifecycleFamily",
    "LifecyclePhase",
    "LifecycleSubscriber",
    "LifecycleSubscriptionDeclaration",
    "ManifestDocument",
    "ManifestLoader",
    "ManifestProvenance",
    "ManifestSource",
    "PermissionRequirement",
    "PluginDiagnostic",
    "PluginKernelConfig",
    "PluginLifecycleContext",
    "PluginLifecyclePhase",
    "PluginManifest",
    "PortT",
    "ProviderBinding",
    "ProviderKey",
    "RetryPolicy",
    "SourceRead",
    "SubscriberBinding",
    "Version",
    "VersionRange",
    "WorktreeLifecycleContext",
    "WorktreeLifecyclePhase",
    "bind_application_port",
]
