"""Provider- and transport-neutral managed-worktree capability (bh-xh8ku.3, bh-055ot.1).

Depends only on ``beadhive-plugins`` — for the capability-slot machinery and the
``worktree.manager`` / ``workspace.binding`` slot declarations (``beadhive_plugins.worktree_slots``)
this package implements, not for anything else. Importing it describes naming policy, the
:class:`WorktreeSpec` / :class:`WorktreeHandle` contract, the capability flags, ports, and the
native Git manager; it never selects or binds a provider itself — that is root composition's
job, exclusively, via ``bind_application_port`` (docs/design/package-class-library-vs-plugin-adr.md
section 5, docs/design/bh-mr9tk.2-worktree-manager-herdr-binding-adr.md).

Root keeps a forwarding facade at the old ``beadhive.modules.worktrees`` import path so existing
consumers keep working unchanged — every name here resolves identically through that facade
(``docs/MODULES.md`` principle 8: compatibility facades are deliberate migration tools).
"""

from __future__ import annotations

from .adapters import (
    NATIVE_PROVIDER_ID,
    CallbackWorktreeInventory,
    NativeGitBranchInspector,
    NativeGitWorktreeManager,
    native_worktree_manager_provider_binding,
)
from .application import (
    DEFAULT_LIMIT,
    DEFAULT_MAX_WORKERS,
    MAX_LIMIT,
    RemovalOutcome,
    WorktreeInventoryService,
    WorktreeLifecycleService,
    all_union_eligible,
    build_inventory_payload,
    classify_entries_concurrently,
    compute_digest,
    execute_removal,
    flag_legacy_root,
    is_zero_delta_rebase,
    ordered_statuses,
    parse_conflict_paths,
    reclaim_empty_parents,
    resolve_batch_evidence,
    split_safe_skipped,
    status_tags,
    union_attributes_text,
    withhold_untrustworthy,
)
from .contracts import (
    WORKSPACE_BINDING,
    WORKTREE_MANAGER,
    WORKTREE_MANAGER_KEY,
    BeadStateLookup,
    BranchInspector,
    ClaimRecords,
    CommandRunner,
    MergeEvidence,
    WorkspaceBindingPort,
    WorktreeCreateObserver,
    WorktreeInventory,
    WorktreeManagerPort,
)
from .domain import (
    BATCH_BRANCH_PREFIX,
    BATCH_LEAF_PREFIX,
    NATIVE_CAPABILITIES,
    WT_PREFIX,
    BindingGap,
    BoundWorktree,
    CommandOutcome,
    ManagedWorktree,
    WorkspaceBindingError,
    WorktreeBinding,
    WorktreeBranchPolicy,
    WorktreeHandle,
    WorktreeInventoryRequest,
    WorktreeInventoryResult,
    WorktreeManagerCapabilities,
    WorktreeManagerError,
    WorktreeRemoved,
    WorktreeSpec,
    WorktreeStatusRequest,
    WorktreeStatusResult,
    apply_prefix,
    bind_worktree,
    branch_suffix,
    leaf_for_branch,
    sanitize_leaf,
)
from .policy import (
    INIT_RULES_CONFIG_KEY,
    BatchEvidence,
    WtClassification,
    WtDisposition,
    WtStatus,
    bead_states,
    classify,
    disposition_relations,
    dispositions_needing_evidence,
    format_disposition,
    parse_disposition,
    read_recorded_fingerprint,
    record_fingerprint,
    rules_fingerprint,
    run_init_rules,
    store_reason,
    untrustworthy,
    warn_drift,
)

__all__ = [
    "BATCH_BRANCH_PREFIX",
    "BATCH_LEAF_PREFIX",
    "DEFAULT_LIMIT",
    "DEFAULT_MAX_WORKERS",
    "INIT_RULES_CONFIG_KEY",
    "MAX_LIMIT",
    "NATIVE_CAPABILITIES",
    "NATIVE_PROVIDER_ID",
    "WORKSPACE_BINDING",
    "WORKTREE_MANAGER",
    "WORKTREE_MANAGER_KEY",
    "WT_PREFIX",
    "BatchEvidence",
    "BeadStateLookup",
    "BindingGap",
    "BoundWorktree",
    "BranchInspector",
    "CallbackWorktreeInventory",
    "ClaimRecords",
    "CommandOutcome",
    "CommandRunner",
    "ManagedWorktree",
    "MergeEvidence",
    "NativeGitBranchInspector",
    "NativeGitWorktreeManager",
    "RemovalOutcome",
    "WorkspaceBindingError",
    "WorkspaceBindingPort",
    "WorktreeBinding",
    "WorktreeBranchPolicy",
    "WorktreeCreateObserver",
    "WorktreeHandle",
    "WorktreeInventory",
    "WorktreeInventoryRequest",
    "WorktreeInventoryResult",
    "WorktreeInventoryService",
    "WorktreeLifecycleService",
    "WorktreeManagerCapabilities",
    "WorktreeManagerError",
    "WorktreeManagerPort",
    "WorktreeRemoved",
    "WorktreeSpec",
    "WorktreeStatusRequest",
    "WorktreeStatusResult",
    "WtClassification",
    "WtDisposition",
    "WtStatus",
    "all_union_eligible",
    "apply_prefix",
    "bead_states",
    "bind_worktree",
    "branch_suffix",
    "build_inventory_payload",
    "classify",
    "flag_legacy_root",
    "classify_entries_concurrently",
    "compute_digest",
    "disposition_relations",
    "dispositions_needing_evidence",
    "execute_removal",
    "format_disposition",
    "is_zero_delta_rebase",
    "leaf_for_branch",
    "native_worktree_manager_provider_binding",
    "ordered_statuses",
    "parse_conflict_paths",
    "parse_disposition",
    "read_recorded_fingerprint",
    "reclaim_empty_parents",
    "record_fingerprint",
    "resolve_batch_evidence",
    "rules_fingerprint",
    "run_init_rules",
    "sanitize_leaf",
    "split_safe_skipped",
    "status_tags",
    "store_reason",
    "union_attributes_text",
    "untrustworthy",
    "warn_drift",
    "withhold_untrustworthy",
]
