"""Forwarding facade — moved to the ``beadhive-plugins`` library package (bh-xh8ku.2).

The typed, framework-independent lifecycle event contracts now live in
:mod:`beadhive_plugins.lifecycle`. This module re-exports the identical objects at the old
import path so existing consumers keep working unchanged; the lifecycle dispatcher stays in
root as composition machinery that binds concrete subscribers to these contracts.
"""

from __future__ import annotations

from beadhive_plugins.lifecycle import (
    AGENT_LAUNCH_EVENTS,
    ALL_LIFECYCLE_EVENTS,
    EVENTS_BY_ID,
    HIVE_EVENTS,
    HOST_EVENTS,
    PLUGIN_EVENTS,
    WORKTREE_EVENTS,
    AgentLaunchLifecycleContext,
    AgentLaunchLifecyclePhase,
    CompensationMode,
    CompensationPolicy,
    ContextT,
    Criticality,
    DeliveryPolicy,
    HiveLifecycleContext,
    HiveLifecyclePhase,
    HostDaemonLifespanComponent,
    HostDaemonLifespanFactory,
    HostDaemonRuntimePort,
    HostDaemonShutdownPhase,
    HostDaemonStartupPhase,
    HostLifecycleContext,
    HostLifecyclePhase,
    Idempotency,
    LifecycleCompensator,
    LifecycleEvent,
    LifecycleFamily,
    LifecyclePhase,
    LifecycleSubscriber,
    PluginLifecycleContext,
    PluginLifecyclePhase,
    RetryPolicy,
    SubscriberBinding,
    WorktreeLifecycleContext,
    WorktreeLifecyclePhase,
)

__all__ = [
    "AGENT_LAUNCH_EVENTS",
    "ALL_LIFECYCLE_EVENTS",
    "EVENTS_BY_ID",
    "HIVE_EVENTS",
    "HOST_EVENTS",
    "PLUGIN_EVENTS",
    "WORKTREE_EVENTS",
    "AgentLaunchLifecycleContext",
    "AgentLaunchLifecyclePhase",
    "CompensationMode",
    "CompensationPolicy",
    "ContextT",
    "Criticality",
    "DeliveryPolicy",
    "HiveLifecycleContext",
    "HiveLifecyclePhase",
    "HostDaemonLifespanComponent",
    "HostDaemonLifespanFactory",
    "HostDaemonRuntimePort",
    "HostDaemonShutdownPhase",
    "HostDaemonStartupPhase",
    "HostLifecycleContext",
    "HostLifecyclePhase",
    "Idempotency",
    "LifecycleCompensator",
    "LifecycleEvent",
    "LifecycleFamily",
    "LifecyclePhase",
    "LifecycleSubscriber",
    "PluginLifecycleContext",
    "PluginLifecyclePhase",
    "RetryPolicy",
    "SubscriberBinding",
    "WorktreeLifecycleContext",
    "WorktreeLifecyclePhase",
]
