"""Generate Typer command groups from the canonical operation catalog.

The catalog stays declarative: it contains no imports of handlers and performs no dispatch.
This composition-root helper accepts an explicit operation-to-handler map, validates the
catalog's naming rules, and turns the catalog projection into Typer registrations.  Application
functions therefore remain the behavior source while names, hidden state, passthrough settings,
and tracing are generated here.

The assembled root tree is catalog-generated by :mod:`beadhive.adapters.cli.tree`.  The focused
``project_cli_group`` helper remains the compatibility construction seam for ``plan`` and
``work`` while their module-owned app objects are still public.
"""

from __future__ import annotations

import hashlib
import inspect
import json
import re
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from functools import wraps
from typing import Any

import typer
from typer.main import get_command

from ...kernel.operations import OperationSpec, operations
from ...kernel.telemetry import TraceVerb

MIGRATED_CLI_GROUPS: tuple[str, ...] = (
    "<root>",
    "alerts",
    "backup",
    "checkpoint",
    "config",
    "contrib",
    "dep",
    "dolt",
    "harness",
    "hive",
    "host",
    "hq",
    "label",
    "mcp",
    "otel",
    "plan",
    "plugin",
    "release",
    "setup",
    "toolchain",
    "work",
    "worktree",
    "wt",
)
HAND_AUTHORED_CLI_GROUPS: tuple[str, ...] = ()

# This narrow rule is part of the original work/plan focused generator, not a generic rule for
# every catalog collection command.  Whole-tree generation validates the catalog declarations
# without retroactively imposing work's opaque-list convention on unrelated application groups.
_SCOPED_LIST_MODE_GROUPS = frozenset({"plan", "work"})

_SINGULAR_EXCEPTIONS = frozenset({"alerts", "harness"})
_MCP_TOOL_EXCEPTIONS = frozenset({"bd_create"})
_RESOURCE_GROUP_EXCEPTIONS = frozenset({"alerts"})
_RETIRED_SURFACE_TOKEN = re.compile(r"(?<![a-z0-9])(?:ws|rig)(?![a-z0-9])", re.I)
_COMMAND_PART = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
_RESOURCE_PARAMETER = re.compile(r"^\{(?P<name>[a-z][a-z0-9_]*)\}$")
_OPAQUE_ARGV_PASSTHROUGH = {
    "mode": "opaque-argv",
    "allow_extra_args": True,
    "ignore_unknown_options": True,
}


class CatalogProjectionError(ValueError):
    """The catalog cannot be projected without violating its declared CLI contract."""


@dataclass(frozen=True)
class ProjectionReport:
    """Deterministic record of one generated Typer group."""

    group: str
    operations: tuple[str, ...]
    paths: tuple[str, ...]
    digest: str


@dataclass(frozen=True)
class HandlerBinding:
    """A core handler plus canonical-parameter to compatibility-parameter aliases."""

    handler: Callable[..., Any]
    parameter_aliases: Mapping[str, str]


def bind_handler(handler: Callable[..., Any], **parameter_aliases: str) -> HandlerBinding:
    """Keep a historical Python signature behind a canonical generated CLI signature."""
    return HandlerBinding(handler=handler, parameter_aliases=parameter_aliases)


def _cli_operation_rows(
    operation_specs: Sequence[OperationSpec],
) -> dict[str, tuple[OperationSpec, dict[str, Any]]]:
    rows: dict[str, tuple[OperationSpec, dict[str, Any]]] = {}
    for operation in operation_specs:
        projection = operation.surfaces.get("cli")
        if projection is not None:
            rows[operation.name] = (operation, projection)
    return rows


def catalog_cli_groups(
    operation_specs: Sequence[OperationSpec] | None = None,
) -> frozenset[str]:
    """Return every top-level CLI group represented by the catalog.

    Leaf commands mounted directly on ``bh`` use the explicit ``<root>`` bucket.
    """
    specs = operations() if operation_specs is None else operation_specs
    groups: set[str] = set()
    for operation in specs:
        projection = operation.surfaces.get("cli")
        if projection is None:
            continue
        parts = projection["path"].split()
        groups.add(parts[0] if len(parts) > 1 else "<root>")
        for alias in projection["aliases"]:
            alias_parts = alias["path"].split()
            groups.add(alias_parts[0] if len(alias_parts) > 1 else "<root>")
    return frozenset(groups)


def _fail(rule: int, detail: str) -> None:
    raise CatalogProjectionError(f"naming convention {rule}: {detail}")


def _reject_retired_surface_tokens(value: str, descriptor: str) -> None:
    if match := _RETIRED_SURFACE_TOKEN.search(value):
        _fail(8, f"retired surface token {match.group(0)!r} in {descriptor}")


def _has_supported_passthrough(projection: dict[str, Any]) -> bool:
    """Reject malformed declarations instead of treating key presence as a list mode."""
    if "passthrough" not in projection:
        return False
    passthrough = projection["passthrough"]
    if (
        not isinstance(passthrough, Mapping)
        or set(passthrough) != set(_OPAQUE_ARGV_PASSTHROUGH)
        or passthrough.get("mode") != "opaque-argv"
        or passthrough.get("allow_extra_args") is not True
        or passthrough.get("ignore_unknown_options") is not True
    ):
        _fail(2, "passthrough must declare the supported nonempty opaque-argv mode metadata")
    return True


def _validate_cli_identity(operation: OperationSpec, projection: dict[str, Any]) -> None:
    path = projection["path"]
    parts = path.split()
    if not parts or any(not _COMMAND_PART.fullmatch(part) for part in parts):
        _fail(1, f"{path!r} is not a singular kebab-case command path")
    group = parts[0]
    if group.endswith("s") and group not in _SINGULAR_EXCEPTIONS:
        _fail(1, f"plural group {group!r} in {path!r}")

    canonical_parts = operation.name.split(".")
    canonical_path = " ".join(canonical_parts)
    if path != canonical_path:
        if canonical_parts[-1] == "list":
            _fail(2, f"collection {operation.name!r} must project with the list verb")
        if parts[-1] == f"{canonical_parts[-1]}s":
            _fail(1, f"per-entity leaf {parts[-1]!r} in {path!r} is plural")
        _fail(1, f"{operation.name!r} must derive the CLI path {canonical_path!r}, got {path!r}")

    if group in _SCOPED_LIST_MODE_GROUPS and canonical_parts[-1] == "list":
        mode_parameters = set(projection["parameters"]) - {"hive"}
        has_passthrough = _has_supported_passthrough(projection)
        if not mode_parameters and not has_passthrough:
            _fail(2, f"collection {path!r} requires list mode flags or declared passthrough modes")


def _validate_cli_parameters(operation: OperationSpec, projection: dict[str, Any]) -> None:
    path = projection["path"]
    parameters = projection["parameters"]
    if len(parameters) != len(set(parameters)):
        _fail(3, f"{path!r} declares duplicate CLI parameters")
    if any(name in {"json", "json_out"} for name in parameters):
        _fail(3, f"{path!r} must bind machine output only to as_json")
    by_name = {parameter.name: parameter for parameter in operation.parameters}
    if "as_json" in parameters:
        declared = by_name.get("as_json")
        if declared is None or declared.schema.get("type") != "boolean" or declared.required:
            _fail(3, f"{path!r} as_json must be a declared optional boolean")


def _validate_resource(operation: OperationSpec, mcp: dict[str, Any], resource: str) -> None:
    if not resource.startswith("beadhive://"):
        _fail(7, f"resource {resource!r} is outside beadhive://")
    rest = resource.removeprefix("beadhive://")
    segments = rest.split("/")
    group = segments[0]
    if not group or not _COMMAND_PART.fullmatch(group):
        _fail(7, f"resource {resource!r} has no valid singular group")
    if group.endswith("s") and group not in _RESOURCE_GROUP_EXCEPTIONS:
        _fail(7, f"resource group {group!r} is plural")

    if len(segments) == 1:
        if not mcp.get("divergence"):
            _fail(7, f"resource {resource!r} requires a valid view segment")
        return
    declared_parameters = set(mcp.get("resource_parameters", ()))
    for index, segment in enumerate(segments[1:], start=1):
        parameter = _RESOURCE_PARAMETER.fullmatch(segment)
        if not segment or (
            not _COMMAND_PART.fullmatch(segment)
            and not (parameter and parameter.group("name") in declared_parameters)
        ):
            kind = "view" if index == 1 else "path"
            _fail(7, f"resource {resource!r} has invalid {kind} segment {segment!r}")


def validate_catalog_generation_rules(
    operation_specs: Sequence[OperationSpec] | None = None,
) -> None:
    """Check all eight naming-ADR rules against generator input.

    Handler-dependent flag and trace checks run in :func:`project_cli_group`; this check covers
    the deterministic identities shared by CLI and MCP projections.
    """
    specs = operations() if operation_specs is None else operation_specs
    for operation in specs:
        _reject_retired_surface_tokens(operation.name, f"operation {operation.name!r}")
        cli = operation.surfaces.get("cli")
        if cli is not None:
            _reject_retired_surface_tokens(cli["path"], f"CLI path {cli['path']!r}")
            _validate_cli_identity(operation, cli)
            _validate_cli_parameters(operation, cli)
            for projection in cli["aliases"]:
                path = projection["path"]
                parts = path.split()
                if not parts or any(not _COMMAND_PART.fullmatch(part) for part in parts):
                    _fail(1, f"{path!r} is not a singular kebab-case command path")
                group = parts[0]
                if group.endswith("s") and group not in _SINGULAR_EXCEPTIONS:
                    _fail(1, f"plural group {group!r} in {path!r}")
                if any(part in {"ls", "lists"} for part in parts[1:]):
                    _fail(2, f"collection path {path!r} must use the list verb")
                _validate_cli_parameters(operation, projection)
                _reject_retired_surface_tokens(path, f"CLI alias {path!r}")

        mcp = operation.surfaces.get("mcp")
        if mcp is None:
            continue
        if tool := mcp.get("tool"):
            derived = operation.name.replace(".", "_")
            exception = operation.name == "bd.create" and tool in _MCP_TOOL_EXCEPTIONS
            if tool != derived and not exception:
                _fail(6, f"tool {tool!r} is not derived as {derived!r}")
        if resource := mcp.get("resource"):
            _validate_resource(operation, mcp, resource)
        for value in filter(None, (mcp.get("tool"), mcp.get("resource"))):
            _reject_retired_surface_tokens(value, f"MCP projection {value!r}")


def _validate_live_flags(
    app: typer.Typer,
    group: str,
    projected: Mapping[str, tuple[OperationSpec, dict[str, Any]]],
) -> None:
    command = get_command(app)
    for verb, leaf in command.commands.items():
        operation, projection = projected[verb]
        expected_parameters = projection["parameters"]
        actual_parameters = [parameter.name for parameter in leaf.params]
        if group in MIGRATED_CLI_GROUPS:
            hive = next((parameter for parameter in leaf.params if parameter.name == "hive"), None)
            if hive is None or [*hive.opts, *hive.secondary_opts] != ["--hive"]:
                _fail(4, f"{group} {verb} requires long-only --hive scope")
        if actual_parameters != expected_parameters:
            if any(
                "--format" in getattr(parameter, "opts", ())
                or parameter.name in {"format", "format_"}
                for parameter in leaf.params
            ):
                _fail(3, f"{group} {verb} exposes undeclared --format machine output")
            raise CatalogProjectionError(
                f"{group} {verb} handler signature differs from catalog "
                f"({actual_parameters!r} != {expected_parameters!r})"
            )
        by_name = {parameter.name: parameter for parameter in operation.parameters}
        for parameter in leaf.params:
            opts = [*getattr(parameter, "opts", ()), *getattr(parameter, "secondary_opts", ())]
            if "--json" in opts and (
                parameter.name != "as_json"
                or opts != ["--json"]
                or not parameter.is_bool_flag
                or by_name["as_json"].schema.get("type") != "boolean"
            ):
                _fail(3, f"{group} {verb} --json must be a canonical boolean as_json flag")
            if parameter.name == "as_json" and "--json" not in opts:
                _fail(3, f"{group} {verb} as_json must expose only --json, got {opts!r}")
            if "--hive" in opts and (parameter.name != "hive" or opts != ["--hive"]):
                _fail(4, f"{group} {verb} --hive must be long-only and bound to hive")


def _canonical_handler(binding: HandlerBinding) -> Callable[..., Any]:
    handler = binding.handler
    aliases = dict(binding.parameter_aliases)
    signature = inspect.signature(handler, eval_str=True)
    unknown = set(aliases.values()) - set(signature.parameters)
    if unknown:
        raise CatalogProjectionError(
            f"handler {handler.__qualname__} has no compatibility parameters {sorted(unknown)!r}"
        )
    canonical_parameters = []
    for parameter in signature.parameters.values():
        canonical = next(
            (name for name, compatibility in aliases.items() if compatibility == parameter.name),
            parameter.name,
        )
        canonical_parameters.append(parameter.replace(name=canonical))

    @wraps(handler)
    def invoke(*args: Any, **kwargs: Any) -> Any:
        for canonical, compatibility in aliases.items():
            if canonical in kwargs:
                kwargs[compatibility] = kwargs.pop(canonical)
        return handler(*args, **kwargs)

    invoke.__signature__ = signature.replace(parameters=canonical_parameters)  # type: ignore[attr-defined]
    return invoke


def project_cli_group(
    app: typer.Typer,
    group: str,
    handlers: Mapping[str, Callable[..., Any] | HandlerBinding],
    *,
    operation_specs: Sequence[OperationSpec] | None = None,
    trace_verb: TraceVerb,
) -> ProjectionReport:
    """Generate ``group``'s Typer leaves from catalog rows and explicit core handlers.

    ``handlers`` is keyed by canonical operation identity (for example ``work.claim``), never
    by a second hand-authored command name.  Its order controls help ordering for compatibility;
    every presentation attribute still comes from the catalog projection.
    """
    if group not in MIGRATED_CLI_GROUPS:
        raise CatalogProjectionError(f"{group!r} is not declared as a migrated CLI group")
    specs = operations() if operation_specs is None else operation_specs
    validate_catalog_generation_rules(specs)
    rows = _cli_operation_rows(specs)
    expected = {
        name
        for name, (_operation, projection) in rows.items()
        if projection["path"].split()[:1] == [group] and len(projection["path"].split()) == 2
    }
    supplied = set(handlers)
    if supplied != expected:
        missing = sorted(expected - supplied)
        extra = sorted(supplied - expected)
        raise CatalogProjectionError(
            f"{group} handler map is incomplete (missing={missing!r}, extra={extra!r})"
        )

    paths: list[str] = []
    resolved_handlers: dict[str, Callable[..., Any]] = {}
    projected: dict[str, tuple[OperationSpec, dict[str, Any]]] = {}
    for operation_name, configured_handler in handlers.items():
        operation, projection = rows[operation_name]
        path = projection["path"]
        path_group, verb = path.split()
        if path_group != group:
            raise CatalogProjectionError(
                f"{operation_name!r} projects to {path!r}, outside {group!r}"
            )
        handler = (
            _canonical_handler(configured_handler)
            if isinstance(configured_handler, HandlerBinding)
            else configured_handler
        )
        resolved_handlers[operation_name] = handler
        _reject_retired_surface_tokens(
            inspect.getdoc(handler) or "", f"generated handler {operation_name!r} docstring"
        )
        traced = trace_verb(operation.name)(handler)
        if getattr(traced, "__otel_verb__", None) != operation.name:
            _fail(5, f"{path!r} lost its trace_verb marker")
        context_settings = None
        if passthrough := projection.get("passthrough"):
            context_settings = {
                "allow_extra_args": passthrough["allow_extra_args"],
                "ignore_unknown_options": passthrough["ignore_unknown_options"],
            }
        app.command(
            verb,
            hidden=projection["declared_hidden"],
            context_settings=context_settings,
        )(traced)
        paths.append(path)
        projected[verb] = (operation, projection)

    _validate_live_flags(app, group, projected)
    material = json.dumps(
        [
            {
                "operation": name,
                "path": rows[name][1]["path"],
                "handler": (
                    f"{inspect.unwrap(handler).__module__}.{inspect.unwrap(handler).__qualname__}"
                ),
            }
            for name, handler in resolved_handlers.items()
        ],
        sort_keys=True,
        separators=(",", ":"),
    ).encode()
    return ProjectionReport(
        group=group,
        operations=tuple(handlers),
        paths=tuple(paths),
        digest=hashlib.sha256(material).hexdigest(),
    )


def generated_callbacks(
    app: typer.Typer, report: ProjectionReport
) -> dict[str, Callable[..., Any]]:
    """Return generated callbacks by operation identity for compatibility re-exports.

    Historically the ``work``/``plan`` module functions were themselves trace-decorated.  The
    generator keeps raw handlers in the binding map, then composition roots re-export these
    callbacks so direct Python callers retain the same tracing behavior as CLI callers.
    """
    callbacks = tuple(command.callback for command in app.registered_commands)
    if len(callbacks) != len(report.operations):
        raise CatalogProjectionError(
            f"{report.group} callback count changed after projection: "
            f"{len(callbacks)} != {len(report.operations)}"
        )
    return dict(zip(report.operations, callbacks, strict=True))


def validate_migration_inventory(
    operation_specs: Sequence[OperationSpec] | None = None,
) -> None:
    """Reject an unnamed catalog group or a group listed in both migration buckets."""
    declared = set(MIGRATED_CLI_GROUPS) | set(HAND_AUTHORED_CLI_GROUPS)
    overlap = set(MIGRATED_CLI_GROUPS) & set(HAND_AUTHORED_CLI_GROUPS)
    if overlap:
        raise CatalogProjectionError(
            f"CLI groups listed as both migrated and hand-authored: {overlap}"
        )
    actual = set(catalog_cli_groups(operation_specs))
    if declared != actual:
        raise CatalogProjectionError(
            f"CLI migration inventory drift (missing={sorted(actual - declared)!r}, "
            f"stale={sorted(declared - actual)!r})"
        )


validate_migration_inventory()
