"""Declarative plugin discovery and typed composition-time capability binding."""

from .binding import bind_application_port
from .contracts import (
    CapabilityBindingError,
    CapabilityKey,
    CapabilityRef,
    CapabilitySelection,
    CliProjection,
    CredentialRequirement,
    CredentialSource,
    DiagnosticCode,
    DiagnosticSeverity,
    DiscoveredPlugin,
    DiscoveryResult,
    ExecutableRequirement,
    ExternalEntryPoint,
    LifecycleSubscriptionDeclaration,
    ManifestDocument,
    ManifestProvenance,
    ManifestSource,
    PermissionRequirement,
    PluginDiagnostic,
    PluginKernelConfig,
    PluginManifest,
    ProviderBinding,
    ProviderKey,
    SourceRead,
    Version,
    VersionRange,
)
from .discovery import (
    BuiltInManifestSource,
    ExternalEntryPointSource,
    discover_plugins,
    parse_kernel_config,
)

__all__ = [
    "BuiltInManifestSource",
    "CapabilityBindingError",
    "CapabilityKey",
    "CapabilityRef",
    "CapabilitySelection",
    "CliProjection",
    "CredentialRequirement",
    "CredentialSource",
    "DiagnosticCode",
    "DiagnosticSeverity",
    "DiscoveredPlugin",
    "DiscoveryResult",
    "ExecutableRequirement",
    "ExternalEntryPoint",
    "ExternalEntryPointSource",
    "ManifestDocument",
    "ManifestProvenance",
    "ManifestSource",
    "LifecycleSubscriptionDeclaration",
    "PermissionRequirement",
    "PluginDiagnostic",
    "PluginKernelConfig",
    "PluginManifest",
    "ProviderBinding",
    "ProviderKey",
    "SourceRead",
    "Version",
    "VersionRange",
    "bind_application_port",
    "discover_plugins",
    "parse_kernel_config",
]
