"""API-first Beadhive command handlers over the pinned Beads v1.3 session.

This distribution never imports the root ``beadhive`` application. The installed ``beadhive``
compatibility shell selects these handlers at its top-level command composition seam and
supplies the narrow ports (gates, state dimensions) that Beads v1.3 does not expose over HTTP.
"""

from __future__ import annotations

from .queue import (
    DECLINE_EMPTY_QUEUE,
    DECLINE_NONE_ELIGIBLE,
    DECLINES,
    QUEUE_CAPABILITIES,
    ClaimNextOutcome,
    QueueCommands,
    by_parent,
    decline,
    direct_children,
    eligible,
    ready_row,
    ready_rows,
    to_bd_json,
)
from .review import (
    APPROVED,
    CHANGES_REQUESTED,
    GATE_ROUTES,
    REVIEW_CAPABILITIES,
    STATE_ROUTES,
    Gate,
    GateLookupFailed,
    GateOperations,
    GateResolveFailed,
    Notice,
    NullObserver,
    ReviewCommands,
    ReviewFailed,
    ReviewObserver,
    ReviewOutcome,
    ReviewPolicy,
    SessionUnavailable,
    StateOperations,
    StateUpdateFailed,
)
from .routing import (
    COORDINATION_OPERATIONS,
    ApiRoute,
    CompatibilityRoute,
    DeniedRoute,
    NullRoutingObserver,
    OperationDenied,
    Route,
    RouteKind,
    RouteMismatch,
    RoutingObserver,
    RoutingTable,
    UnknownOperation,
    default_table,
)

__all__ = [
    "APPROVED",
    "CHANGES_REQUESTED",
    "COORDINATION_OPERATIONS",
    "DECLINE_EMPTY_QUEUE",
    "DECLINE_NONE_ELIGIBLE",
    "DECLINES",
    "GATE_ROUTES",
    "QUEUE_CAPABILITIES",
    "REVIEW_CAPABILITIES",
    "STATE_ROUTES",
    "ApiRoute",
    "ClaimNextOutcome",
    "CompatibilityRoute",
    "DeniedRoute",
    "Gate",
    "GateLookupFailed",
    "GateOperations",
    "GateResolveFailed",
    "Notice",
    "NullObserver",
    "NullRoutingObserver",
    "OperationDenied",
    "QueueCommands",
    "ReviewCommands",
    "ReviewFailed",
    "ReviewObserver",
    "ReviewOutcome",
    "ReviewPolicy",
    "Route",
    "RouteKind",
    "RouteMismatch",
    "RoutingObserver",
    "RoutingTable",
    "SessionUnavailable",
    "StateOperations",
    "StateUpdateFailed",
    "UnknownOperation",
    "by_parent",
    "decline",
    "default_table",
    "direct_children",
    "eligible",
    "ready_row",
    "ready_rows",
    "to_bd_json",
]
